{{/*
Service name (used for metadata.name, labels, selectors).
*/}}
{{- define "node-service.name" -}}
{{- required "values.name is required" .Values.name -}}
{{- end -}}

{{/*
Common labels applied to every resource generated by the chart.
*/}}
{{- define "node-service.labels" -}}
app.kubernetes.io/name: {{ include "node-service.name" . }}
app.kubernetes.io/instance: {{ .Release.Name }}
app.kubernetes.io/managed-by: argocd
app.kubernetes.io/part-of: burraco
{{- end -}}

{{/*
Selector labels (subset of labels, immutable after first apply).
*/}}
{{- define "node-service.selectorLabels" -}}
app.kubernetes.io/name: {{ include "node-service.name" . }}
app.kubernetes.io/instance: {{ .Release.Name }}
{{- end -}}
