apiVersion: v1
kind: Service
metadata:
  name: redis
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: redis
    app.kubernetes.io/part-of: ai-burraco
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: redis
  ports:
    - name: redis
      port: {{ .Values.service.port }}
      targetPort: redis
      protocol: TCP
