name: ranking-service
image:
  repository: ghcr.io/abaddon/ai-burraco-ranking-service
  tag: 72ca56cdda4d9de497e7abd65d7b9b6ba5731acf
service:
  port: 8087
database:
  serviceDb: burraco_ranking
ingress:
  pathPrefixes:
    - /api/v1/ranking
