name: social-service
image:
  repository: ghcr.io/abaddon/ai-burraco-social-service
  tag: e8e939689b22fb71ce0432c3f6e221be3d9b678f
service:
  port: 8083
database:
  serviceDb: burraco_social
ingress:
  pathPrefixes:
    - /api/v1/social
  websocketPaths:
    - /ws/social
