name: lobby-service
image:
  repository: ghcr.io/abaddon/ai-burraco/lobby-service
  tag: 7ff3cf5fe08d15b862da15554f75211983fb5526
service:
  port: 8084
database:
  serviceDb: burraco_lobby
ingress:
  pathPrefixes:
    - /api/v1/lobby
  websocketPaths:
    - /ws/lobby
env:
  SPRING_PROFILES_ACTIVE: prod
  GAME_SERVICE_URL: http://game-service.burraco.svc.cluster.local:8085
