name: player-service
image:
  repository: ghcr.io/abaddon/ai-burraco-player-service
  tag: 440727d65c8564fe397057cd92d96df9fd360f3c
service:
  port: 8082
database:
  serviceDb: burraco_player
ingress:
  pathPrefixes:
    - /api/v1/players
