name: ranking-service
image:
  repository: ghcr.io/abaddon/ai-burraco-ranking-service
  tag: f448932e0dfe495faca2bb82c6c1cf4aade47a42
service:
  port: 8087
database:
  serviceDb: burraco_ranking
ingress:
  pathPrefixes:
    - /api/v1/ranking
