name: player-service
image:
  repository: ghcr.io/abaddon/ai-burraco-player-service
  tag: b41704dae9cc3291bc47dd9e9ea341bb64278fee
service:
  port: 8082
database:
  serviceDb: burraco_player
ingress:
  pathPrefixes:
    - /api/v1/players
