name: ranking-service
image:
  repository: ghcr.io/abaddon/ai-burraco-ranking-service
  tag: 9c8fec6e0821c846cb2ea2dc5963e103ebeda555
service:
  port: 8087
database:
  serviceDb: burraco_ranking
ingress:
  pathPrefixes:
    - /api/v1/ranking
