name: lobby-service
image:
  repository: ghcr.io/abaddon/ai-burraco-lobby-service
  tag: 0d22fa658d99456ff85fa3c4a6e976f1924ec9fc
service:
  port: 8084
database:
  serviceDb: burraco_lobby
ingress:
  pathPrefixes:
    - /api/v1/lobby
  websocketPaths:
    - /ws/lobby
env:
  SPRING_PROFILES_ACTIVE: prod
  GAME_SERVICE_URL: http://game-service.burraco.svc.cluster.local:8085
