name: player-service
image:
  repository: ghcr.io/abaddon/ai-burraco-player-service
  tag: 8f1eb20f5e6e23c209557b3aba4d2ec579e967be
service:
  port: 8082
database:
  serviceDb: burraco_player
ingress:
  pathPrefixes:
    - /api/v1/players
