name: social-service
image:
  repository: ghcr.io/abaddon/ai-burraco-social-service
  tag: cb39528008a7b88c9734152b2ac96e9c854e3608
service:
  port: 8083
database:
  serviceDb: burraco_social
ingress:
  pathPrefixes:
    - /api/v1/social
  websocketPaths:
    - /ws/social
