name: social-service
image:
  repository: ghcr.io/abaddon/ai-burraco-social-service
  tag: 28d25bf20bb7ecc8a4175ea7e11df190aa8d5966
service:
  port: 8083
database:
  serviceDb: burraco_social
ingress:
  pathPrefixes:
    - /api/v1/social
  websocketPaths:
    - /ws/social
