---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: brevo-api-key
  namespace: burraco
spec:
  encryptedData:
    BREVO_API_KEY: AgAaCu/MUcHpjxbXIyf6usWgu5SfMPbU0Z4PCBF3M2yYo7DZPaI3QmI/2GzWsFSkWrSSSC3xxbfkNSEmoKVFiYg57MOlmXkucHNVkday8BywR+hXLNo1OVMfpxp3DOoKJ5FP4JVAeDk0ZDeJvyPL9RPNsKWJi4fUt/nlRrXEsFgfklPlLllL9TrsmZny2ok5ObO51GRzPrYNK5RUwnpNWGiYplleqqGFiMI88CNAVqNkcg2THmmvEMIkPyG2ixl3JRR/najDb+vd7KAElKliGI5f1qvnRVLrfgYLDhynyfcC2FYRSiN8wPQMVJvdwnqexM1Ue1LhMQo/6ottww+aLRDHNBpTS8PA2iI4KK4CTizucyZgTDr1rz5FaVrGqi4j1VMzYj8wkvRbM9c3jU87307wE5vELcqLw8p9lMVHu4bG+YZfXX1hASfVGsGF1AUwJajRGp1LfcQyQIlnKqWKpHHOLm1AHeBjcsJAM/A5bWhlSrHhJSKYvVB3ArvF61CMuN4NEatz0tEjQuMREOofhArL0yHZHeMCEuQ8NVLelX9/Eym0d4teglNfA89G261RcG+kAyZH6ky5tRUAF0AAUZVeUIX6mGhO0Go6og01BLpCzMarlTzH5vyhCDPSvHJoUaAh1lGPVh+XfN9mjUzeYl0FcOkdjaPKaXHCHYcni56Ds7cOahgAvDMpyspYFuUTsPLdINAGnPmBHDPSF4UyDP7gENiw3tRDNE2ZRP3977SyyXj5fhDNg40Yvl80HZhkgRaDnYX4covTGesNs0VNm4fBoyr3kSX2jaattB9xP+O2TIf5imL6vL3p3g==
  template:
    metadata:
      name: brevo-api-key
      namespace: burraco
