---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: brevo-api-key
  namespace: burraco
spec:
  encryptedData:
    BREVO_API_KEY: AgCkMa/vGMBUcU7Gpni0AA6Q/G5JnJFFU3Rc0oNrFWCenejxkxg56D7HqjTXWN55+runUZjgkHclAOL4kTeuHG6uOZcgEKF5d9d1b4pBwjr/D7/7sGmdU3jO8V4b6UvYgt+63/mpr8PYxzj+1iODQJeMNuRwqBIk45fBVZp5K3uZjWOb0g43DG8ea1ZYgSGF09eMnsj6tGUjLViMkX9z0kemEA6m2WzH+Ygbpb5c9FtHJ9rhoJ9cwbT/X2OQvE+Fxfka7ZTJMWEhlkG7pq/AIzsBrd9U6m+nkaJQxS7OY/Xsm7cJFpV2k6QMrWUCctd8GMPJ6iM/5KS7lYWliF7phkspMvcmAzer3XB6EZjftO56MTSSh/jyiw3SH9WjiTqnPKZEQtup1U76VUf6YQxI6ryTWHf5cabeGcXDh3qJ7QfGT9O3FpDl5aHmqZ5Vc2gC6cCaaZeSNwMmOjI1P8NT7DtWQNZWMc6E5TTVhpg9IcQ4fgjCi6UvWuhf4+5ERuWEnLYukQUNcXwmMfcMslZQnvYe5GZSOABWn66KxexLaYGE+TtU5u+6t1HGeNb2G8efNNdFfA/pbrg7ZQ/dbsSWvhMP3orYGvcAzabD7uThvFPdopApGnaLTZq60JF1Ia4qx76e9sv2nWUGDpriBSiwzQ/DwGN6cMl4DRNa0SaJBZzU/CeRIvQH4V+5moC9eHb/hZND1MDb/G8TfC74mtsvtZJs+aQzgwp3aR42hF/8kObutHyl
  template:
    metadata:
      name: brevo-api-key
      namespace: burraco
