---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: brevo-api-key
  namespace: burraco
spec:
  encryptedData:
    BREVO_API_KEY: AgClFpkbYpgJEsEdgH9/lV5ayG9yY1i1DkXF1X12huVOva6b8mGzlhy3aXY2kkkVGU2XT92ru3IByx+HQzM7+jBo9ZNJmZ835Dd22yTnMFNzK8KGEeI75X7Rb0MIqsPuDU/HOBjRMnaFL/bTPMlQg+XaY1mwEDTB0n84CHEIYV8J4TBGo83HspmjwHGgQ01F79iDvWlxX/8BLKDhrLjYkJ4IT3iCv8ato4lh7wdhw7gEyINRxGChB9OFadMxQdAZAnKfM1U5NzAss2uJ8vthEIl7qWQmKqQqIHFqkOqPpVxNJuAq5O0PY04x5yQTmjO3cRMFiKr7ahQqDPgLFO3+8ngpBT2UvHIVxJF4ITMUVKpqg+iAX7YsOI37I80q7euf1ndNIFQbxjVapQVHG436GWtbMdeOQEW2HqFFthcwTWqvsKetZOZC/jr/lMtUwfkPulcd/zP1DkoCdPjviEgVSBakk+Z6NSBFh23bsoe1WgTnMgD7z14oziiNuizbbIPFFUvwdK1O+QJCfixHvZg/Nmz1tjR9p/HovlAyJLT7ill4odMMLKgP1NHnQeCnJSFa/fUBYoDIW7OlQz+rgzabMtzWL0QrMNDKhes9uDii1EsCKHhfvJjqvfCyibiKXG9TQ0kujhZcyUK0v77HnU2J8oqjyh+/RwCkUBhDcNEOotugT+8K4HXMPu96fjlezLkeWCThR0mgAMWKAcHgbG6zrNUT1kw+GwCLxzJM2rY2zhFfDwqLx2Cfv83FESBdT9SEzEY0ItkxqPNNtBSn7DsOY25ZQeXp1eMR/zkDNbw0oBVieGZw3JMoVHb1jw==
  template:
    metadata:
      name: brevo-api-key
      namespace: burraco
