---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: cloudflare-api-token
  namespace: cert-manager
spec:
  encryptedData:
    api-token: AgBfOgtXc6Rd1vCNVtIzvCyi8o3vdMU5Md6sn4KEeSCE63QdCnVAUYHbUAkbbjm8aC4fJ0BksxqEauriYKJTbGHg9WCjjdJjqI0Rvunevsvr+ZKh9J+cbhYTyJDsMEfL6Jb0h2Sc8y21NEbSx2cHxT1Gku25708vITIDZyNOyJYQKngMGcOeKaPwZ1FZoMnYPlfbTzyQ+bN2PDfCB9OA/cnNZy/j0YEOxIWzs4fkFLbh9EExbgMEpf6np5U50hSDt3dPcmnTiSBmUZbiZQpli9RHpjuwoUyJ86azX80jsqA9MA8qVHRsHgfJMQSpgsSGeyRrsBLZeemIoqDb2gaYl+x94Eta24fAkEpdQBaUNCVd61qOGsgULtsnpZq7g6Xg8+Fiewg8qMyp+5u6rt0rCtznZwekazHs2GtcDpfJrvBvQOFoda1U7uxFEKlIOSuljhwhE3O0rx/XQVHuNHNPXQgDYGQAHLRq4QT5qX82LN6eH7y+UKJdC/RkfFxYoKXjJ8AGsoyA9BRGJulLKPJ7t32UxWV0T9saYiro1BdiQJVUuSIcyvQKTeN9/lIRzMK9dQDVDiiTfAa7p4Fjw2uP+H6Wt7eIuzcI0hzdSEqRunV+MGlIhQLkiMgS10f295HaEl+ClT9CkJNVnQIyICyREmxCzK/eSKrGBBEWdAsm7oZryhSOMy3A3tqNHxV0pDHOMd6tneYSNWsy56QKfbEPofQGl0ddNRzc1CRrvXm2iMCo7LxKNDt/1yA27CJisnd3vrE7IZ7QKQ==
  template:
    metadata:
      name: cloudflare-api-token
      namespace: cert-manager
