---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: postgres-credentials
  namespace: infra
spec:
  encryptedData:
    password: AgB2vFaJXj2REscI+3HD5rsdb4ZT31Y8lwAo/Nw2RBf+T0z8Lv4kXE2EGlVt+whpxUBgesGBCzKytIMb/+yo1Xcw6OJjCLTD04pYLHAE9c417d5ZFKGvdbm2ubPJywALHjSL/4wHE3+o+USNOinU2zmhiHuve+Jc0ecPjl85F0gGdDoY1AWo4/V+JuRwu0MXeiAlWqe2titSXLqK8QEnFudk/ot//36fjXc44yO3sJ93PsZJ8xhAFtG1eKMaq2wC/jLygK+tzeZSoHXKxC+2KEcHB+6xPFwghGMLIpoHO5zynLpuGSAefKfcKpEARamXXMmNR6ww1pLlqUSaZ/2kpcz1+pd2Brw7r7aykl4QnCZIKiz1WbXnEY+KJHWMqufAGVAxEwr/SeswEUC1YsAgDB0N2Q307uO3UhbdQoEXcJFMwWRKPj3JtAHWarKgg2V+/qpPlRFDIhmsgdvLV/az/3ilS9ugZ7TSINijz5tNBxt9q4iDwVYnReK/uN7MoQG9TzL4yvegeVtx1uW2P5SyKe4FGALCiiYnyazPf4z1/jArbS5jZasFEPIsn2HKDLSpM7mRbYVdtsVD/ex8nguX6mci4x2ypYJUfICav7sZ4hkjlZUNBKo0rc0naPO+HBCAsyi/ulhnKSBWPZGLBkSklbKlUZaOXc1CdD7yYlelyq3ZE6JCIDgO7sHPgbvGG4GR4B10Tx/03An9IrFJR9rAVuyggjkTDg==
    username: AgAz0V6JkEQV057lUjYZRXBqD32RZ1nozGmpP2R+770vEzwToD63sojHFyNaOlvpR+CFnv7HBrlKAMt3Ek1ZbYbHUQ0wJIcPfojWczravm226UJcOZPcCTzDA7IIH62LdaW5wpvvLyF4/P/B1YuPbXnvgv3oeWbDN2h87hB4rsTXJ4vgCd8lVn2zVC71LaGK0GoeDtgElla7K37Vvy9A1KC9zXivlccowvva5h/nshz/3PR91FTZrMbuo/g74PLeBfJyueoUZB3JSkHSPZz5IyYaqSYSJ9Lavw4VEsx6CiOBdAkDxFfqamkYiqRmOCmyKDcy+VQ7QHt7eScLe5uxtEQlJ36R+dMng0oFv4D6qiC7QD2sa7cH5CKm0/ZtI3k6mCDJVm2PMVp9ex0FQGRZVilR7jlkozaIoffp/BwJiMtQ/lhn9VGVHozp9TKTWJw91ERagcqPGkFk9R+m5OnBH0f2yB3W7xp/wkJObnatcmmO954Nc4CiT5fPJCRtHONtorBAky7l9H8DCQc0kAxHLL96KihtAeFS+JN3S8lpx7e3LXXD9lravJhiJo2fEf9rNBYlpRbz+VSfqQmepXMVfj7EUpSYUMVJTsophPLLUWOQ9c/EpywGo7KJZdker6H9F2td3CzfvyK4JfLC985twXZLPFzbK5KZ+Tk1M5Av4TXygu7vLAMM0iO7KwAvVLyyyMU5hW/QUn+e
  template:
    metadata:
      name: postgres-credentials
      namespace: infra
