---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: redis-password
  namespace: burraco
spec:
  encryptedData:
    REDIS_PASSWORD: AgAoQoObcMDMelosiKkwL6jYRuYXuMrcZUNZR/SPHdArLYg4LVKgvnuIrGGTc9d6Rc6bAcDXEH+iIM7vqFEkR7hIiuxuGe6BGx/+oYlcPfa390f3vSiPF6CFGIH6CTABMb/37X/4HIfe+5aEJt9jQtutPKFI9bfoej7NylZbTICl6zQU48gU2DBe/XuNHFuzKvbj+pXsDYGBwDWLqUsz/FCwcyib+9SbFRAcHZLQt9RTLmCGLdDyGGOVmFhRBHp2PqI+yg68+wYfTmaeb79QtcLelKFGQBOA20NjK3cmo0M4QYptMvqwOCZq1S+eQpRPXsN1/p26UdW+ny9A17dibD0EJ+OTBmd5PQ62JwwD+qYoj52FzAI8RRzt0BHBjZdK8JBIa1YCpjsS843jZiyYwAD52xw5Yn62XeGw9AZeTUuTtgQWZitk/cMYgrO5kyXm7tu7TSiWvlIOp67hnk4uDp2Lbwyqfqk/Y3WBYB8aEktnl4ZZuR0y6+EFEJG4UAti5E/8zPASuPiwhBQZyBRnE4+XcceqIyEEHp6fI5B+I4Um5L9rpc0TFy+PRHepRATg2ews3L0nEgJoP2BANoqGReRPKVnawE1/YiGNHBNsNOCQT6ne0hr7gKWtZt63JyKjG4T7vBkb8bB3z7xUuNpqeJ3BWwdtVFXFrnYWAurVq24Uij/V0/jeF5do+ugUAb+a5BcrLcxj+VxrB1xQuQrN23y0EUK6GA==
    SPRING_DATA_REDIS_PASSWORD: AgCoEonhiGwUzvEzEas9JeSedc8bHKrDiNedbqFun9u19Yu66jLkZZC5Ap2L08py8LGvZC+b7Org0x1hK1RkkZMy2NyLEQ+efzlmzECgEHpDQu4FpG0tZEnw6uX11AMzWDmNR3vN36AKxP+2JQDs5t3MvVAeR5ZZ4KbHh/6Agt15As85wr/Z9cZ5suLtkpg/v+YO/GMEi+gjGSuWln98zDF7ui/M+lwBsg1R/VLHSuJhAZAZOUNca1FrvyB6cIH2cLay3T1A6YIniLfWkEU2veQjj2q68qiexWldQqCdsZzuPWFjW338rhiDm20a+TwE7BY0ua5qAF97sG/a9RB0RIXg3NkzuqP6N1QcEpz1T+YDazHUnfPq7x2J7a/pLFKbaIT8/68ts56XS6BkqGD0zqspQi/pOJoIemmK7FiQKDOPF+5StiNrTIjj2SAowKcZJzeqqh4ln24bZ2AdiTV/f8M8iRfiroS0mF2Lzv1rxjhR3/jPZIcI+7FNJZ5VyAMVMz1RkB3GHFrBijQ/6sPoVfeqYadW2/XK9JpBYrOhXcyfBnsogs7A33tePf1m+6X3gyEr4gNsJWVA7pmXnCJQzWnv/hPlA8Vp2j8u5JWe1vaIpR6LAbd9xDfFJWkbifVCn51fR4iuIPu+Km20YSWBE1zvDFFpn0mJ4EC3JplhZ+/FpJ5ZODAXMLpUbDZLDBW5wUS1KgFT9nCtz/nEit/D1K/MtdLC2Q==
  template:
    metadata:
      name: redis-password
      namespace: burraco
