---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: redis-password
  namespace: burraco
spec:
  encryptedData:
    REDIS_PASSWORD: AgBxyrgNy2IDdERmKc32nvnvHqNEOgxQ3UzTcNbqd8XEdiIKW5wzPdEqAWX4iS2JP0/gGJG6jCLtgAr7BNlqQYqsYXMfpVm76NEx8QAo1CSM+2xwdo6euOopxyzVjLfUsbmrvjwxHyW742QEesEhxZNc2P93x0XQDb+qjO4IV2+cGClm5nrrAsptb2mUmCkY1hY9QYSnPM4vTdDg0vh2h1FUXr/XbZOZGp7+I05gCEwvNy/lS8NVIB+QZ8eaoQ7PZHsGXziOMmo6ufdAyRMKoai9oF3UMJ4Pu7W4JUlXe9zrKVKWfbao2oeiT8xucsT1yL/3bLgL4f5uTwopaLQ1yM7/ZWnDQDVdbGyPtgvXj06nJV2nUgRQcHeWygp9QFvE+c1tEftrPGp7bEPxmBofd2cT2k70d+yfiigs0mUkF9BszfJFIBkooM46Of+JhYMuDW1gCT5ngKtlW9s0L9vJ/s8kNlhZ8cWcudz5L5clJMoBilVbbh4F/ILNdFimUKaEnvVaZNU1ShQS1BTJWauKrKaUkZ0EWv3jizJ2zr6bTM5RwAxHDqfnJTCww6t2xsvrLJFdRgWEc8N6HL9Z3l0VsSQNl8cBstEdYG2L/BrqO0YXbOrNfCRnu/GHogqfPViEI1Z0zop0pLnnJF5zfrf0G/7ygoEbv7tD/WOXmEqTplbj4i1CqjAsVCI5ryTbI6bvFfSh3i5l5MI0VUebf4xmylX+hmhEHg==
    SPRING_DATA_REDIS_PASSWORD: AgAr2pfOWuc3kUahpZKN2gkCWh6OtYh+2lLvqi8AliVLlvnvHm/zrWqnui/WhMF0+v2kaA3QAxEQdOQhtwArie1gaxbN9G5AoXRmK0hEOysYtWl26I09H3AtlbgBkpj1x5O9g9oP4/NO3CCHwLL1sUeNCo6YhhbZxpcZ0p0aMtYtHvreZqDSj5vd1s18jehJq9PEqmFyBdvYHb4KpBO+tSmAmqfGuoit2g5JZZru+tfA4u71GKu06SYpj2eWK/MYmIO3KzDpmRqSawX+YMKkAYY1NgKb0Ov8bNmkHyaeL7CNjV1nRwCX+SZuyMwJwRn4A2kSVln+8SJksKDAholcfZzUh53RVXAayk7wClqRd1T6f3y0XBTSVCUn0GKtHLKGEjgBDLfMpteFAYx2092RZlWQmuEPHzqoOXfuXzlXBe3r0BUlRT2e+O1eBr4ubYERGvzTsfYXOf+YHMhbkfArxptRDwiq+LzfTjMr9GxdLSwwWU6h5G8I7lj68FageUxkv9ZCUw53+oEfZuDvR2HDxY1iM0IzAUXLoDYeXib/jfVn2sZfzXA1SNuVNWy7cbJeWfHWfIOSaDp6U1lJyBMesC6aLO8dlFaW0pUL82CS682CUnjA4GYMaFAvIUQpLT9KKGzCUO6eZtzIXGpmcU38d7aX6PCxlU8Dbw5sD9iO6g5xdZdmKfDDtatog6pbmrfONSzr5Iscre2Vc0+rE/HLG3kx2D6bAA==
  template:
    metadata:
      name: redis-password
      namespace: burraco
