---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: redis-password
  namespace: infra
spec:
  encryptedData:
    REDIS_PASSWORD: AgA0lsr+oeMD3uAAdVmL2SgaiM8v5HJg4PNTDMl4Vq1iayUW8lwCG6YZ1cYbG0jkQ/ZK6VhkTj3s0+A5bMsuxVUryo7dO9MKZEg18T8pt+URwx00TBaL4A/N9Z/R6EPk2HplCk6RQuPtMGlVuuWFg8VcTlgNAN7eZ1W26btSwGaoOARzxyJeNkTUWQFhSNj6VkBD8wXrL5eU8H/4E+SRiRS2DDO8ovlkDQmqB/kuBZwC6GcsAGWFq9h+XR2ntl2THcwMAZIIPctfx6KpLLvayRpgsu3zNPmiOQTiSWN9DYSBRfO5wp0c/6IkFzlMfuffTWd2LquOAXowOrwvtpKvU2M6WnjFESlqSjakNCtQcAF7qP4+hCQ6+rL0F4wggbkzTEB8GSFAihWTiM/+hGFPDV3F4gFR7J4k9cgRO1k+RTn/lBfmv+iONJS9efxgAX+tMu4rrvReeF7Q64qk7FiddEFmYMwpZmwWarW3xVe0A8YksUMuop+/3XotTDH/O8VPzFYFapgEned/EI8MrdGUy2cJtrZ3k1PToOZ67PkStKhxEPbHFxs8TUPReeC1Coqln7Hsg92imtwI44eRK7X3KDAPQqa7ryNK9IuoNUNT9w/LxgsxwUPEsGfzt32GI7VTwbi/rEcb7kRg95dtkqElGCX3tAwSSNZv/LNXaiB2oy0qL/tQnQGL0L6d0UYBplJuh+8a6VGdStJBkRj6Wc5KC8fLEgpW0Q==
  template:
    metadata:
      name: redis-password
      namespace: infra
